// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD96SLnUtHqsRDe3KNBsbXTSjOuf4sTaC4',
    appId: '1:676397645276:web:76710731e90fb29638a319',
    messagingSenderId: '676397645276',
    projectId: 'xachievments',
    authDomain: 'xachievments.firebaseapp.com',
    storageBucket: 'xachievments.appspot.com',
    measurementId: 'G-K9FV41CJSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1caw7hJtx6qs1XCn2d95s-mZ84__83_0',
    appId: '1:676397645276:android:c1f532ccba5bbe7738a319',
    messagingSenderId: '676397645276',
    projectId: 'xachievments',
    storageBucket: 'xachievments.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4AwX5xhMhvAWtYJJ2-vHKq6oxuU6PNbM',
    appId: '1:676397645276:ios:eae5c162f459137e38a319',
    messagingSenderId: '676397645276',
    projectId: 'xachievments',
    storageBucket: 'xachievments.appspot.com',
    iosBundleId: 'com.example.xAxhievments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4AwX5xhMhvAWtYJJ2-vHKq6oxuU6PNbM',
    appId: '1:676397645276:ios:77acfee2190b6b3e38a319',
    messagingSenderId: '676397645276',
    projectId: 'xachievments',
    storageBucket: 'xachievments.appspot.com',
    iosBundleId: 'com.example.xAxhievments.RunnerTests',
  );
}
